---
Sequence :
 - Actimize03_RefPrice :
    numrows : 10
    extension : '.dat'
 - Actimize01_Orders : 
    numrows : 100
    extension : '.dat'
 - Actimize02_Executions : 
    numrows : 50
    extension : '.dat'